#!/usr/bin/env bash
# Kuk Calendar — local iOS setup (run on a Mac with Xcode + Flutter).
#
# This repo keeps only pubspec.yaml + lib/ + assets/; the native ios/ scaffold is
# generated by `flutter create` (same as the Android build). This script does the
# one-time iOS configuration so you can open the project in Xcode, sign with your
# own Apple team, and Archive → TestFlight / App Store.
#
# Usage (from the repo root, on macOS):
#   bash scripts/setup-ios.sh
#   open ios/Runner.xcworkspace      # then: Signing & Capabilities → your Team → Product → Archive
#
# Idempotent: safe to re-run. Requires macOS (PlistBuddy) — iOS can only be built
# on a Mac; there is no cross-platform iOS build.

set -euo pipefail

if [[ "$(uname)" != "Darwin" ]]; then
  echo "ERROR: iOS setup must run on macOS (needs Xcode + PlistBuddy)." >&2
  exit 1
fi

echo "==> Generating iOS scaffold (keeps lib/ + pubspec + assets)…"
flutter create --org com.kuklabs --project-name kukcalendar --platforms=ios .

PBX=ios/Runner.xcodeproj/project.pbxproj
PLIST=ios/Runner/Info.plist

echo "==> Bundle id → com.kuklabs.calendar"
sed -i '' -E 's/PRODUCT_BUNDLE_IDENTIFIER = com\.kuklabs\.kukcalendar;/PRODUCT_BUNDLE_IDENTIFIER = com.kuklabs.calendar;/g' "$PBX"

echo "==> Display name → Kuk Calendar"
/usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName Kuk Calendar" "$PLIST" \
  || /usr/libexec/PlistBuddy -c "Add :CFBundleDisplayName string 'Kuk Calendar'" "$PLIST"

echo "==> Calendar-usage descriptions (device_calendar)"
/usr/libexec/PlistBuddy -c "Add :NSCalendarsUsageDescription string 'Kuk Calendar shows your device calendar events alongside your Kuklabs events.'" "$PLIST" 2>/dev/null || true
/usr/libexec/PlistBuddy -c "Add :NSCalendarsFullAccessUsageDescription string 'Kuk Calendar shows your device calendar events alongside your Kuklabs events.'" "$PLIST" 2>/dev/null || true

echo "==> kukcalendar:// deep link (Google SSO return)"
/usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes array" "$PLIST" 2>/dev/null || true
/usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0:CFBundleURLName string com.kuklabs.calendar" "$PLIST" 2>/dev/null || true
/usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0:CFBundleURLSchemes array" "$PLIST" 2>/dev/null || true
/usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0:CFBundleURLSchemes:0 string kukcalendar" "$PLIST" 2>/dev/null || true

echo "==> flutter pub get"
flutter pub get

echo "==> App launcher icon (KukLabs 'K' — same mark as Android)"
dart run flutter_launcher_icons -f flutter_launcher_icons_ios.yaml

cat <<'DONE'

✅ iOS configured. Next:
   1. open ios/Runner.xcworkspace
   2. Runner target → Signing & Capabilities → select your Team (automatic signing)
   3. Product → Archive → Distribute App → TestFlight (or App Store Connect)

   Or from the CLI once signing is set in Xcode:
     flutter build ipa
   (the .ipa lands in build/ios/ipa/ — upload via Transporter or Xcode Organizer)
DONE
