#!/usr/bin/env bash
# Kuk Calendar — local iOS setup (run on a Mac with Xcode + Flutter).
#
# This repo keeps only pubspec.yaml + lib/ + assets/; the native ios/ scaffold is
# generated by `flutter create` (same as the Android build). This script does the
# one-time iOS configuration so you can open the project in Xcode, sign with your
# own Apple team, and Archive → TestFlight / App Store.
#
# Usage (from the repo root, on macOS):
#   bash scripts/setup-ios.sh
#   open ios/Runner.xcworkspace      # then: Signing & Capabilities → your Team → Product → Archive
#
# Idempotent: safe to re-run. Requires macOS (PlistBuddy) — iOS can only be built
# on a Mac; there is no cross-platform iOS build.

set -euo pipefail

if [[ "$(uname)" != "Darwin" ]]; then
  echo "ERROR: iOS setup must run on macOS (needs Xcode + PlistBuddy)." >&2
  exit 1
fi

echo "==> Generating iOS scaffold (keeps lib/ + pubspec + assets)…"
flutter create --org com.kuklabs --project-name kukcalendar --platforms=ios .

PBX=ios/Runner.xcodeproj/project.pbxproj
PLIST=ios/Runner/Info.plist

echo "==> Bundle id → com.kuklabs.calendar"
sed -i '' -E 's/PRODUCT_BUNDLE_IDENTIFIER = com\.kuklabs\.kukcalendar;/PRODUCT_BUNDLE_IDENTIFIER = com.kuklabs.calendar;/g' "$PBX"

echo "==> iOS deployment target → 15.0 (App Store rejects < 15; flutter create defaults to 12)"
sed -i '' -E 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9]+(\.[0-9]+)?;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' "$PBX"
# Podfile: flutter create leaves `# platform :ios, '12.0'` commented — set it to 15.0.
if [ -f ios/Podfile ]; then
  sed -i '' -E "s/^# *platform :ios, '[0-9.]+'/platform :ios, '15.0'/" ios/Podfile
  sed -i '' -E "s/^platform :ios, '[0-9.]+'/platform :ios, '15.0'/" ios/Podfile
fi

echo "==> Sign in with Apple entitlement (com.apple.developer.applesignin)"
# The login screen shows the native Apple button on iOS; without this entitlement
# the ASAuthorizationController sheet fails at runtime (error 1000 / "not handled").
# Write it into the scaffold AND wire CODE_SIGN_ENTITLEMENTS into the Runner target
# so a CLI archive (flutter build ipa) enables it too — not only a manual Xcode
# "+ Capability" click. Xcode automatic signing then enables the capability on the
# App ID when it archives with a paid team.
cat > ios/Runner/Runner.entitlements <<'ENT'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.developer.applesignin</key>
	<array>
		<string>Default</string>
	</array>
</dict>
</plist>
ENT
# Anchor on `INFOPLIST_FILE = Runner/Info.plist;` — present only in the Runner
# target's build configs, never RunnerTests — so the tests target is untouched.
if ! grep -q "CODE_SIGN_ENTITLEMENTS = Runner/Runner.entitlements;" "$PBX"; then
  sed -i '' -E 's#(INFOPLIST_FILE = Runner/Info\.plist;)#\1\'$'\n''\t\t\t\tCODE_SIGN_ENTITLEMENTS = Runner/Runner.entitlements;#g' "$PBX"
fi

echo "==> Display name → Kuk Calendar"
/usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName Kuk Calendar" "$PLIST" \
  || /usr/libexec/PlistBuddy -c "Add :CFBundleDisplayName string 'Kuk Calendar'" "$PLIST"

echo "==> Calendar-usage descriptions (device_calendar)"
/usr/libexec/PlistBuddy -c "Add :NSCalendarsUsageDescription string 'Kuk Calendar shows your device calendar events alongside your Kuklabs events.'" "$PLIST" 2>/dev/null || true
/usr/libexec/PlistBuddy -c "Add :NSCalendarsFullAccessUsageDescription string 'Kuk Calendar shows your device calendar events alongside your Kuklabs events.'" "$PLIST" 2>/dev/null || true

echo "==> Purpose strings required by Apple review (ITMS-90683)"
# Apple rejected build 1 with ITMS-90683: bundled SDKs (sign_in_with_apple,
# share/file plugins) reference PhotoLibrary/Camera/Microphone APIs, so a
# user-facing purpose string is MANDATORY even though the app never invokes them.
# Use "Set" then fall back to "Add" so re-runs update rather than duplicate.
/usr/libexec/PlistBuddy -c "Set :NSPhotoLibraryUsageDescription 'Kuk Calendar can attach a photo to an event.'" "$PLIST" 2>/dev/null \
  || /usr/libexec/PlistBuddy -c "Add :NSPhotoLibraryUsageDescription string 'Kuk Calendar can attach a photo to an event.'" "$PLIST" 2>/dev/null || true
/usr/libexec/PlistBuddy -c "Set :NSCameraUsageDescription 'Kuk Calendar can attach a photo to an event.'" "$PLIST" 2>/dev/null \
  || /usr/libexec/PlistBuddy -c "Add :NSCameraUsageDescription string 'Kuk Calendar can attach a photo to an event.'" "$PLIST" 2>/dev/null || true
/usr/libexec/PlistBuddy -c "Set :NSMicrophoneUsageDescription 'Kuk Calendar can attach a voice note to an event.'" "$PLIST" 2>/dev/null \
  || /usr/libexec/PlistBuddy -c "Add :NSMicrophoneUsageDescription string 'Kuk Calendar can attach a voice note to an event.'" "$PLIST" 2>/dev/null || true

echo "==> Export-compliance + bundle name (avoids the encryption prompt on every upload)"
# ITSAppUsesNonExemptEncryption=false: the app uses only standard HTTPS, which is
# exempt — declaring it here stops App Store Connect from holding the build for a
# manual export-compliance answer.
/usr/libexec/PlistBuddy -c "Set :ITSAppUsesNonExemptEncryption false" "$PLIST" 2>/dev/null \
  || /usr/libexec/PlistBuddy -c "Add :ITSAppUsesNonExemptEncryption bool false" "$PLIST" 2>/dev/null || true
# CFBundleName (short name) — some validators warn when it is missing.
/usr/libexec/PlistBuddy -c "Set :CFBundleName KukCalendar" "$PLIST" 2>/dev/null \
  || /usr/libexec/PlistBuddy -c "Add :CFBundleName string KukCalendar" "$PLIST" 2>/dev/null || true

echo "==> kukcalendar:// deep link (Google SSO return)"
/usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes array" "$PLIST" 2>/dev/null || true
/usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0:CFBundleURLName string com.kuklabs.calendar" "$PLIST" 2>/dev/null || true
/usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0:CFBundleURLSchemes array" "$PLIST" 2>/dev/null || true
/usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0:CFBundleURLSchemes:0 string kukcalendar" "$PLIST" 2>/dev/null || true

echo "==> flutter pub get"
flutter pub get

echo "==> App launcher icon (KukLabs 'K' — same mark as Android)"
dart run flutter_launcher_icons -f flutter_launcher_icons_ios.yaml

cat <<'DONE'

✅ iOS configured (incl. Sign in with Apple entitlement). Next:
   1. open ios/Runner.xcworkspace
   2. Runner target → Signing & Capabilities → select your Team (automatic signing).
      "Sign in with Apple" already appears — this script wrote Runner.entitlements
      and wired it into the project. With a paid team, automatic signing enables the
      capability on your App ID when it archives. (If signing complains that the App
      ID lacks the capability, add it once at developer.apple.com → Identifiers →
      com.kuklabs.calendar → Sign In with Apple, then re-archive. Required by Apple
      guideline 4.8 because the app also offers Google login.)
   3. Product → Archive → Distribute App → TestFlight (or App Store Connect)

   Or from the CLI once signing is set in Xcode:
     flutter build ipa
   (the .ipa lands in build/ios/ipa/ — upload via Transporter or Xcode Organizer)
DONE
